[bot]
token = "your_token"
admin_chat_id = -10000000


[logging]
level = "INFO"
event_level = "WARNING"

[date]
# Параметр для корректировки числителя и знаменателя:
# если 1 сентября — это числитель, то параметр равен 0, а если знаменатель — то 1.
numerator = 1
timezone = "Europe/Moscow"
college_cron = "0 */3 * * *"

[university]
groups = [
    "groups",
]
teachers = [
    "teachers"
]
rooms = ["rooms"]

# Студенты - сотрудники кафедры
[university.students]
"student" = "group"


[college]
# ID, с которого начинается нумерация занятий колледжа в базе данных расписания.
# ВСЕГДА должно быть больше максимального id занятий университета!
id_const = 1000
app_url = "https://app.volsu.ru/api/schedule/lesson"
api_url = "https://volsu.1450983-cl92470.tw1.ru/api/{type}/bot"
teachers = [
    "teachers"
]

# Преподаватели с ошибкой в фамилии в расписаниях
[aliases]
"Иванов И.И" = ["Иваннов И.И.", "Иванов Т.И."]